# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_alert.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formAlert(object):
    def setupUi(self, formAlert):
        formAlert.setObjectName("formAlert")
        formAlert.resize(401, 161)
        self.buttonOk = QtWidgets.QPushButton(formAlert)
        self.buttonOk.setGeometry(QtCore.QRect(160, 130, 89, 25))
        self.buttonOk.setObjectName("buttonOk")
        self.labelMessage = QtWidgets.QLabel(formAlert)
        self.labelMessage.setGeometry(QtCore.QRect(10, 10, 381, 111))
        self.labelMessage.setText("")
        self.labelMessage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelMessage.setWordWrap(True)
        self.labelMessage.setObjectName("labelMessage")

        self.retranslateUi(formAlert)
        self.buttonOk.clicked.connect(formAlert.buttonOk_clicked)
        QtCore.QMetaObject.connectSlotsByName(formAlert)

    def retranslateUi(self, formAlert):
        _translate = QtCore.QCoreApplication.translate
        formAlert.setWindowTitle(_translate("formAlert", "Внимание!"))
        self.buttonOk.setText(_translate("formAlert", "OK"))
