# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt forms/form_regUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_regUser(object):
    def setupUi(self, form_regUser):
        form_regUser.setObjectName("form_regUser")
        form_regUser.setWindowModality(QtCore.Qt.NonModal)
        form_regUser.resize(781, 271)
        form_regUser.setMinimumSize(QtCore.QSize(781, 271))
        self.gridLayout_2 = QtWidgets.QGridLayout(form_regUser)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.buttonRegistration = QtWidgets.QPushButton(form_regUser)
        self.buttonRegistration.setObjectName("buttonRegistration")
        self.gridLayout.addWidget(self.buttonRegistration, 4, 0, 1, 2)
        self.label_18 = QtWidgets.QLabel(form_regUser)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 0, 0, 1, 2)
        self.label_19 = QtWidgets.QLabel(form_regUser)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_17 = QtWidgets.QLabel(form_regUser)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout.addWidget(self.label_17)
        self.labelCSVSearch = QtWidgets.QLineEdit(form_regUser)
        self.labelCSVSearch.setObjectName("labelCSVSearch")
        self.horizontalLayout.addWidget(self.labelCSVSearch)
        self.buttonCSVSearch = QtWidgets.QPushButton(form_regUser)
        self.buttonCSVSearch.setObjectName("buttonCSVSearch")
        self.horizontalLayout.addWidget(self.buttonCSVSearch)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        self.buttonAdditionalInfo = QtWidgets.QPushButton(form_regUser)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonAdditionalInfo.setFont(font)
        self.buttonAdditionalInfo.setObjectName("buttonAdditionalInfo")
        self.gridLayout.addWidget(self.buttonAdditionalInfo, 2, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(form_regUser)
        self.buttonAdditionalInfo.clicked.connect(form_regUser.buttonAdditionalInfo_clicked)
        self.buttonCSVSearch.clicked.connect(form_regUser.buttonCSVSearch_clicked)
        self.buttonRegistration.clicked.connect(form_regUser.buttonRegistration_clicked)
        QtCore.QMetaObject.connectSlotsByName(form_regUser)

    def retranslateUi(self, form_regUser):
        _translate = QtCore.QCoreApplication.translate
        form_regUser.setWindowTitle(_translate("form_regUser", "Редактировать пользователя"))
        self.buttonRegistration.setText(_translate("form_regUser", "Зарегистрировать"))
        self.label_18.setText(_translate("form_regUser", "<html><head/><body><p align=\"center\">Регистрация множества пользователей</p></body></html>"))
        self.label_19.setText(_translate("form_regUser", "<html><head/><body><p>Для множественной регистрации вам нужно создать CSV-таблицу в кодировке UTF-8. Используемый разделитель - знак запятой &quot;<span style=\" font-weight:600;\">,</span>&quot; (настоятельно рекомендуется использовать <a href=\"https://sheets.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Google Таблицы</span></a>). Первая строка отводится под заголовки. Обязательные заголовки:</p>\n"
"<ol>\n"
"<li>lastname</li>\n"
"<li>firstname</li>\n"
"<li>primaryEmail</li>\n"
"<li>orgUnitPath</li>\n"
"</ol>\n"
"</body></html>"))
        self.label_17.setText(_translate("form_regUser", "Файл:"))
        self.buttonCSVSearch.setText(_translate("form_regUser", "Найти CSV..."))
        self.buttonAdditionalInfo.setText(_translate("form_regUser", "Дополнительная информация о регистрации через файл"))
