# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt forms/form_loader.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_loader(object):
    def setupUi(self, form_loader):
        form_loader.setObjectName("form_loader")
        form_loader.resize(301, 41)
        form_loader.setMinimumSize(QtCore.QSize(301, 41))
        form_loader.setMaximumSize(QtCore.QSize(301, 41))
        self.progressBar = QtWidgets.QProgressBar(form_loader)
        self.progressBar.setGeometry(QtCore.QRect(10, 10, 281, 23))
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(form_loader)
        QtCore.QMetaObject.connectSlotsByName(form_loader)

    def retranslateUi(self, form_loader):
        _translate = QtCore.QCoreApplication.translate
        form_loader.setWindowTitle(_translate("form_loader", "Загрузка"))
        self.progressBar.setFormat(_translate("form_loader", "%v/%m"))
