# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainForm(object):
    def setupUi(self, mainForm):
        mainForm.setObjectName("mainForm")
        mainForm.setWindowModality(QtCore.Qt.ApplicationModal)
        mainForm.resize(800, 600)
        mainForm.setMinimumSize(QtCore.QSize(800, 600))
        mainForm.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(mainForm)
        self.centralwidget.setObjectName("centralwidget")
        self.treeOrgUnits = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeOrgUnits.setGeometry(QtCore.QRect(10, 10, 256, 531))
        self.treeOrgUnits.setColumnCount(1)
        self.treeOrgUnits.setObjectName("treeOrgUnits")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeOrgUnits)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.tableUsers = QtWidgets.QTableWidget(self.centralwidget)
        self.tableUsers.setGeometry(QtCore.QRect(280, 10, 511, 531))
        self.tableUsers.setObjectName("tableUsers")
        self.tableUsers.setColumnCount(4)
        self.tableUsers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsers.setHorizontalHeaderItem(3, item)
        self.tableUsers.horizontalHeader().setDefaultSectionSize(127)
        self.tableUsers.verticalHeader().setDefaultSectionSize(31)
        self.tableUsers.verticalHeader().setMinimumSectionSize(21)
        mainForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menu)
        self.menu_2.setObjectName("menu_2")
        mainForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainForm)
        self.statusbar.setObjectName("statusbar")
        mainForm.setStatusBar(self.statusbar)
        self.action_2 = QtWidgets.QAction(mainForm)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(mainForm)
        self.action_3.setObjectName("action_3")
        self.actionGoogle_Workspace = QtWidgets.QAction(mainForm)
        self.actionGoogle_Workspace.setObjectName("actionGoogle_Workspace")
        self.menu_2.addAction(self.action_2)
        self.menu_2.addAction(self.action_3)
        self.menu.addAction(self.menu_2.menuAction())
        self.menu.addAction(self.actionGoogle_Workspace)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(mainForm)
        QtCore.QMetaObject.connectSlotsByName(mainForm)

    def retranslateUi(self, mainForm):
        _translate = QtCore.QCoreApplication.translate
        mainForm.setWindowTitle(_translate("mainForm", "Управление Google Workspace"))
        self.treeOrgUnits.headerItem().setText(0, _translate("mainForm", "Организационные подразделения"))
        __sortingEnabled = self.treeOrgUnits.isSortingEnabled()
        self.treeOrgUnits.setSortingEnabled(False)
        self.treeOrgUnits.topLevelItem(0).setText(0, _translate("mainForm", "Корень"))
        self.treeOrgUnits.topLevelItem(0).child(0).setText(0, _translate("mainForm", "Студенты"))
        self.treeOrgUnits.topLevelItem(0).child(0).child(0).setText(0, _translate("mainForm", "Очное отделение"))
        self.treeOrgUnits.topLevelItem(0).child(0).child(1).setText(0, _translate("mainForm", "Заочное отделение"))
        self.treeOrgUnits.topLevelItem(0).child(1).setText(0, _translate("mainForm", "Работники"))
        self.treeOrgUnits.setSortingEnabled(__sortingEnabled)
        item = self.tableUsers.horizontalHeaderItem(0)
        item.setText(_translate("mainForm", "Фамилия"))
        item = self.tableUsers.horizontalHeaderItem(1)
        item.setText(_translate("mainForm", "Имя"))
        item = self.tableUsers.horizontalHeaderItem(2)
        item.setText(_translate("mainForm", "Отчество"))
        item = self.tableUsers.horizontalHeaderItem(3)
        item.setText(_translate("mainForm", "Адрес электронной почты"))
        self.menu.setTitle(_translate("mainForm", "Настройки"))
        self.menu_2.setTitle(_translate("mainForm", "Электронная почта"))
        self.action_2.setText(_translate("mainForm", "Проверка подключения"))
        self.action_3.setText(_translate("mainForm", "Настройка"))
        self.actionGoogle_Workspace.setText(_translate("mainForm", "Google Workspace"))
